// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbypSnhL4b6yeS1xtFalvRqY6AswZV-Pw',
    appId: '1:570496241326:web:6980de31db94c4f017a73f',
    messagingSenderId: '570496241326',
    projectId: 'kw-inventory',
    authDomain: 'kw-inventory.firebaseapp.com',
    storageBucket: 'kw-inventory.appspot.com',
    measurementId: 'G-B0YPR2MFXC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChuIFWOz97ZSY13ba6EKPpJ_7b4rG5lMI',
    appId: '1:570496241326:android:c46b56d0bec50c1417a73f',
    messagingSenderId: '570496241326',
    projectId: 'kw-inventory',
    storageBucket: 'kw-inventory.appspot.com',
  );
}
